FROM retcon85/toolchain-sms:1.1-slim

# EXAMPLE
# install ohmyzsh
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y install zsh
RUN zsh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# END:EXAMPLE
